server: 
  context-path: /authority_service
  port: 8888

datasource: 
  type: com.alibaba.druid.pool.DruidDataSource  
  url: jdbc:mysql://10.9.21.225:3306/power?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 'Qiao#19810817'
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 1  
  maxActive: 2  
  initialSize: 1  
  timeBetweenEvictionRunsMillis: 3000  
  minEvictableIdleTimeMillis: 300000  
  validationQuery: SELECT 'ZTM' FROM DUAL  
  testWhileIdle: true  
  testOnBorrow: false  
  testOnReturn: false 
  
# REDIS (RedisProperties)
spring: 
  redis: 
    database: 0
    host: 10.9.21.201
    port: 6379

  pool: 
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0   