
spring: 
  profiles: 
    active: "@activatedProperties@"
    
mybatis: 
  typeAliasesPackage: com.galaxy.authority.bean
  mapperLocations: classpath:mapper/*.xml
  
web:
  loginFilter:
    excludes: /webjars,/swagger,/api-docs,/login/userLogin,/user/updatePwd,/user/getUserById,/user/getUserResource,/user/getResources,/user/getUserScope,/role/selectRoleIdByUserId,/role/selectRoleCodeByUserId,/depart/getLeafDepartList,/user/getUsersByKey,/user/getUserByIds,/user/findUserByName,/user/getUsersByDepId,/user/getShareUserList,/user/getCreadIdInfo,/depart/getDeptIdByDeptName,/user/resetPasswordForApp