
server: 
  context-path: /authority_service
  port: 8888
  
spring: 
  profiles: 
    active: dev
    
mybatis: 
  typeAliasesPackage: com.galaxy.authority.bean
  mapperLocations: classpath:mapper/*.xml