
spring: 
  profiles: 
    active: "@activatedProperties@"
    
mybatis: 
  typeAliasesPackage: com.galaxy.authority.bean
  mapperLocations: classpath:mapper/*.xml
  
  
#下面配置的这些URL都不需要验证sessionID，即强制放行，如果写新接口共其他方直接调用都需要在此添加白名单  
web:
  loginFilter:
    excludes: /webjars,/swagger,/api-docs,/login/userLogin,/user/updatePwd,/user/getUserById,/user/getUserResource,/user/getResources,/user/getUserScope,/role/selectRoleIdByUserId,/role/selectRoleCodeByUserId,/depart/getLeafDepartList,/user/getUsersByKey,/user/getUserByIds,/user/findUserByName,/user/getUsersByDepId,/user/getShareUserList,/user/getCreadIdInfo,/depart/getDeptIdByDeptName,/user/resetPasswordForApp,/login/userLoginForApp,/role/getRoleCodeByUserId,/depart/getDeptInfo,/depart/getCareerLineList,/user/getUserList,/login/allResourceToUser,/brain/selectDepIdByUserId,/role/getUserFromDepartRole