

  
jdbc: 
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.9.11.232:3306/fx_db?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: fxuser
  password: fxdb_Fp9EPkG2